export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';

export const LOGOUT = 'LOGOUT';

export const INFO_RECIEVED = "INFO_RECIEVED";
export const INFO_FAILED = "INFO_FAILED";

export const SUGGESTIONS_RECIEVED = "SUGGESTIONS_RECIEVED";
export const SUGGESTIONS_FAILED = "SUGGESTIONS_FAILED";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECIEVE_MATCHES = "RECIEVE_MATCHES";