export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCEED = "REGISTER_SUCCEED";

export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";

export const SEND_RESET_PASSWORD_SUCCESS = "SEND_RESET_PASSWORD_SUCCESS";
export const SEND_RESET_PASSWORD_FAIL = "SEND_RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCEED = "LOGIN_SUCCEED";
export const TOKEN_ERROR = "TOKEN_ERROR";
export const TOKEN_ERROR_REMOVE = "TOKEN_ERROR_REMOVE";

export const LOGOUT = "LOGOUT";

export const INFO_RECIEVED = "INFO_RECIEVED";
export const INFO_FAILED = "INFO_FAILED";
export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS";
export const UPDATE_INFO_FAIL = "UPDATE_INFO_FAIL";
export const ADD_TAG = "ADD_TAG";
export const ADD_TAG_FAILED = "ADD_TAG_FAILED";
export const REMOVE_TAG = "REMOVE_TAG";
export const REMOVE_IMG = "REMOVE_IMG";
export const ADD_IMG = "ADD_IMG";
export const RESET_LOCATION_SUCCESS = "RESET_LOCATION_SUCCESS";
export const RESET_LOCATION_FAIL = "RESET_LOCATION_FAIL";
export const GET_IMG_SUCCESS = "GET_IMG_SUCCESS";
export const GET_IMG_FAIL = "GET_IMG_FAIL";

export const SUGGESTIONS_RECIEVED = "SUGGESTIONS_RECIEVED";
export const SUGGESTIONS_FAILED = "SUGGESTIONS_FAILED";
export const SUGGESTIONS_SORT_AGE = "SUGGESTIONS_SORT_AGE";
export const SUGGESTIONS_SORT_DISTANCE = "SUGGESTIONS_SORT_DISTANCE";
export const SUGGESTIONS_SORT_FAME = "SUGGESTIONS_SORT_FAME";
export const SUGGESTIONS_SORT_COMMON_TAGS = "SUGGESTIONS_COMMON_TAGS";
export const SUGGESTIONS_FILTER = "SUGGESTIONS_FILTER";
export const SUGGESTIONS_REACT_SUCCESS = "SUGGESTIONS_REACT_SUCCESS";
export const SUGGESTIONS_REACT_FAIL = "SUGGESTIONS_REACT_FAIL";

export const NEW_MESSAGE = "NEW_MESSAGE";
export const RECEIVE_CONVO = "RECEIVE_CONVO";
export const RECIEVE_MATCHES = "RECIEVE_MATCHES";
export const SET_RECEIVER = "SET_RECEIVER";

export const SET_SEARCH_DATA_SUCCESS = "SET_SEARCH_DATA_SUCCESS";
export const SET_SEARCH_DATA_FAIL = "SET_SEARCH_DATA_FAIL";
export const GET_SEARCH_OPTIONS = "GET_SEARCH_OPTIONS";
export const SEARCH_SORT_AGE = "SEARCH_SORT_AGE";
export const SEARCH_SORT_DISTANCE = "SEARCH_SORT_DISTANCE";
export const SEARCH_SORT_FAME = "SEARCH_SORT_FAME";
export const CHANGE_SELECTED_TAGS = "CHANGE_SELECTED_TAGS";
export const GET_SEARCH_IMAGE_SUCCESS = "GET_SEARCH_IMAGE_SUCCESS";
export const GET_SEARCH_IMAGE_FAIL = "GET_SEARCH_IMAGE_FAIL";

export const RECEIVE_NOTIFICATIONS = "RECEIVE_NOTIFICATIONS";

export const RECEIVE_HISTORY = "RECEIVE_HISTORY";

export const VISIT_USER = "VISIT_USER";
export const BLOCK_USER = "BLOCK_USER";
export const REPORT_USER = "REPORT_USER";
export const UNLIKE_USER_SECCESS = "UNLIKE_USER_SECCESS";
export const UNLIKE_USER_FAIL = "UNLIKE_USER_FAIL";

export const ACTIVATE_SOCKET = "ACTIVATE_SOCKET";

export const HOST = "http://e1r4p14.1337.ma:5000/api"