export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';

export const LOGOUT = 'LOGOUT';

export const INFO_RECIEVED = "INFO_RECIEVED";
export const INFO_FAILED = "INFO_FAILED";
export const UPDATE_INFO = "UPDATE_INFO";
export const ADD_TAG = "ADD_TAG";
export const ADD_TAG_FAILED = "ADD_TAG_FAILEDs";
export const REMOVE_TAG = "REMOVE_TAG";

export const SUGGESTIONS_RECIEVED = "SUGGESTIONS_RECIEVED";
export const SUGGESTIONS_FAILED = "SUGGESTIONS_FAILED";

export const NEW_MESSAGE = "NEW_MESSAGE";
export const RECEIVE_CONVO = "RECEIVE_CONVO";
export const RECIEVE_MATCHES = "RECIEVE_MATCHES";
export const SET_RECEIVER = "SET_RECEIVER";

export const SET_SEARCH_DATA = "SET_SEARCH_DATA";
export const GET_SEARCH_OPTIONS = "GET_SEARCH_OPTIONS";
export const CHANGE_SELECTED_TAGS = "CHANGE_SELECTED_TAGS";

export const RECEIVE_NOTIFICATIONS = "RECEIVE_NOTIFICATIONS"